main: com.matt4499.msmp.Main
version: 1.0
api-version: 1.18
description: mSMP
author: Matt4499
name: mSMP
commands:
  afk:
    description: Toggles your AFK status
    usage: /afk
  tell:
    description: Sends a message to a player
    usage: /tell <player> <message>
  msg:
    description: Sends a message to a player
    usage: /msg <player> <message>
  message:
    description: Sends a message to a player
    usage: /message <player> <message>
  whisper:
      description: Sends a message to a player
      usage: /whisper <player> <message>
  r:
    description: Sends a message to the last player you messaged.
    usage: /r <message>
    aliases: [reply]
  f:
    description: Press F to pay respects.
    usage: /f
    aliases: [pressftopayrespects]
  report:
    description: Report a user to staff
    usage: /report [player] [reason]
  pog:
    description: Pog/poggers/pogchamp
    usage: /pog
  l:
    description: Toss the L to a player
    usage: /l [player]
  givecrate:
    description: Give a player a crate
    usage: /givecrate <player>
  votekey:
    permission: votekey.give
    description: Vote for a key
    usage: /votekey [player]
  trash:
    description: Trash can
    usage: /trash
  tp:
    permission: staff.tp
    description: Teleport to a player
    usage: /tp <player>
  tpc:
    permission: staff.tpc
    description: Teleport to coordinates
    usage: /tpc <x> <y> <z>
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  staffmode:
    permission: staff.staffmode
    description: Toggles staff mode
    usage: /staffmode
    aliases: [sm]
  tpa:
    description: Request a teleport to a player
    usage: /tpa <player>
    aliases: [tpask]
  tpayes:
    description: Accept a teleport request
    usage: /tpayes <player>
    aliases: [tpaccept, tpyes]
  punish:
    permission: staff.punish
    description: Punish a player
    usage: /punish <player>
    aliases: [p]
  rules:
    description: View the rules
    usage: /rules
  back:
    description: Teleport back to the last location
    usage: /back
  clearchat:
    description: Clear the chat
    usage: /clearchat
    aliases: [cc]
  ccb:
    description: Ban player then clear chat
    usage: /ccb <player>
  show:
    description: Show off the item in your hand
    usage: /show
  freeze:
    permission: staff.freeze
    description: Freeze a player
    usage: /freeze <player>
  sethome:
    description: Set your home
    usage: /sethome <name>
  home:
    description: Teleport to your home
    usage: /home <name>
  delhome:
    description: Delete your home
    usage: /delhome <name>
  homes:
    description: View your homes
    usage: /homes
  warp:
    description: Warp to a warp
    usage: /warp <name>
  setwarp:
    description: Set a warp
    usage: /setwarp <name> <description>
  delwarp:
    permission: staff.delwarp
    description: Delete a warp
    usage: /delwarp <name>
  warps:
    description: View warps
    usage: /warps
  warpinfo:
    description: View warp info
    usage: /warpinfo <name>
    permission: staff.warpinfo
  seen:
    description: View when a player was last seen
    usage: /seen <player>
  farmworld:
    description: Teleport to the farmworld
    usage: /farmworld
    aliases: [fw, farmingworld]
